"""strange_table

Revision ID: 24973a90231a
Revises: 0033149c936d
Create Date: 2024-12-05 18:59:55.400224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24973a90231a'
down_revision = '0033149c936d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strange_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rainfall_in_inches', sa.Integer(), nullable=True),
    sa.Column('rainfall_in_mm', sa.Float(), nullable=True),
    sa.Column('good_runoff', sa.Float(), nullable=True),
    sa.Column('average_runoff', sa.Float(), nullable=True),
    sa.Column('bad_runoff', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('strange_table')
    # ### end Alembic commands ###
