"""lulc_add_column

Revision ID: 89c0d451a06e
Revises: 24973a90231a
Create Date: 2024-12-06 05:15:06.326719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89c0d451a06e'
down_revision = '24973a90231a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lulc', schema=None) as batch_op:
        batch_op.add_column(sa.Column('catchment', sa.String(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lulc', schema=None) as batch_op:
        batch_op.drop_column('catchment')

    # ### end Alembic commands ###
