"""tj_rec_status

Revision ID: 0033149c936d
Revises: 51f3c28c63c7
Create Date: 2024-12-04 06:36:43.352515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0033149c936d'
down_revision = '51f3c28c63c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('territory_joins', schema=None) as batch_op:
        batch_op.alter_column(
            'rec_status',
            existing_type=sa.INTEGER(),
            type_=sa.Boolean(),
            existing_nullable=False,
            postgresql_using="rec_status::boolean"
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('territory_joins', schema=None) as batch_op:
        batch_op.alter_column(
            'rec_status',
            existing_type=sa.Boolean(),
            type_=sa.INTEGER(),
            existing_nullable=False,
            postgresql_using="CASE WHEN rec_status THEN 1 ELSE 0 END"
        )

    # ### end Alembic commands ###
