"""add industry columns

Revision ID: 3575945df29e
Revises: 894c05b287c3
Create Date: 2024-12-15 02:03:54.671465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3575945df29e'
down_revision = '894c05b287c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('block_industries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('count', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('block_industries', schema=None) as batch_op:
        batch_op.drop_column('count')

    # ### end Alembic commands ###
