"""add transfer columns

Revision ID: 894c05b287c3
Revises: 113ae61375a5
Create Date: 2024-12-15 01:28:59.078370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '894c05b287c3'
down_revision = '113ae61375a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('block_water_transfers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_approved', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('created_on', sa.DateTime(), nullable=True))
        batch_op.drop_constraint('block_water_transfers_block_territory_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'])
        batch_op.create_foreign_key(None, 'block_territory', ['bt_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('block_water_transfers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('block_water_transfers_block_territory_id_fkey', 'block_territory', ['id'], ['id'])
        batch_op.drop_column('created_on')
        batch_op.drop_column('is_approved')
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###
