"""added_progress

Revision ID: ad6fd0b265a7
Revises: d9c1279e0ab0
Create Date: 2025-01-04 09:13:15.150835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad6fd0b265a7'
down_revision = 'd9c1279e0ab0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('block_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('table_id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('block_progress', schema=None) as batch_op:
        batch_op.drop_column('table_id')

    # ### end Alembic commands ###
