"""added_progress

Revision ID: d9c1279e0ab0
Revises: 07b6f93b20e7
Create Date: 2025-01-04 09:07:40.284381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9c1279e0ab0'
down_revision = '07b6f93b20e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('block_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('block_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bt_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bt_id'], ['block_territory.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['block_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('block_progress')
    op.drop_table('block_category')
    # ### end Alembic commands ###
