"""added wb

Revision ID: 5361e1b81d1b
Revises: 1490ef88a19e
Create Date: 2024-04-29 19:16:15.582519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5361e1b81d1b'
down_revision = '1490ef88a19e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('water_bodies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('district_code', sa.Integer(), nullable=True),
    sa.Column('village_code', sa.Integer(), nullable=True),
    sa.Column('wb_type_id', sa.Integer(), nullable=True),
    sa.Column('water_spread_area', sa.Float(), nullable=True),
    sa.Column('max_depth', sa.Float(), nullable=True),
    sa.Column('storage_capacity', sa.Float(), nullable=True),
    sa.Column('longitude', sa.String(length=80), nullable=True),
    sa.Column('lattitude', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wb_master',
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('villages_mp',
    sa.Column('id', sa.Integer(), server_default=sa.text("nextval('villages_id_seq'::regclass)"), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('census_code', sa.Integer(), nullable=True),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('block_id', 'district_id', 'code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('villages_mp')
    op.drop_table('wb_master')
    op.drop_table('water_bodies')
    # ### end Alembic commands ###
