"""add coefficient livestockcensus

Revision ID: 23d4f5c65f14
Revises: 5c851b044498
Create Date: 2024-10-26 23:38:46.129363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23d4f5c65f14'
down_revision = '5c851b044498'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coefficients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('entity', sa.String(length=80), nullable=False),
    sa.Column('coefficient', sa.Float(), nullable=False),
    sa.Column('coefficient_unit', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('livestock_census',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coefficient_id', sa.Integer(), nullable=False),
    sa.Column('livestock_quantity', sa.Integer(), nullable=False),
    sa.Column('village_id', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['coefficient_id'], ['coefficients.id'], ),
    sa.ForeignKeyConstraint(['village_id'], ['villages.id'], ),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('livestock_census')
    op.drop_table('coefficients')
    # ### end Alembic commands ###
