"""add livestocks crops

Revision ID: 33d7e4939bed
Revises: ef136c0d80a6
Create Date: 2024-11-06 18:03:45.805858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33d7e4939bed'
down_revision = 'ef136c0d80a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('coefficient', sa.Float(), nullable=False),
    sa.Column('remarks', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('livestocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('coefficient', sa.Float(), nullable=False),
    sa.Column('remarks', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crop_census', schema=None) as batch_op:
        batch_op.add_column(sa.Column('crop_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'crops', ['crop_id'], ['id'])

    with op.batch_alter_table('livestock_census', schema=None) as batch_op:
        batch_op.add_column(sa.Column('livestock_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'livestocks', ['livestock_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('livestock_census', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('livestock_id')

    with op.batch_alter_table('crop_census', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('crop_id')

    op.drop_table('livestocks')
    op.drop_table('crops')
    # ### end Alembic commands ###
