"""add groundwater waterbody

Revision ID: 4b8433d76e72
Revises: 23d4f5c65f14
Create Date: 2024-10-29 00:38:56.982925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b8433d76e72'
down_revision = '23d4f5c65f14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waterbody_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('waterbody_type', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('groundwater_extractions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stage_of_extraction', sa.Float(), nullable=False),
    sa.Column('rainfall', sa.Float(), nullable=False),
    sa.Column('recharge', sa.Float(), nullable=False),
    sa.Column('discharge', sa.Float(), nullable=False),
    sa.Column('extractable', sa.Float(), nullable=False),
    sa.Column('extraction', sa.Float(), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('waterbodies_census',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spread_area', sa.Float(), nullable=False),
    sa.Column('storage_capacity', sa.Float(), nullable=False),
    sa.Column('max_depth', sa.Float(), nullable=False),
    sa.Column('longitude', sa.String(length=80), nullable=True),
    sa.Column('latitude', sa.String(length=80), nullable=True),
    sa.Column('waterbody_type_id', sa.Integer(), nullable=False),
    sa.Column('village_id', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.ForeignKeyConstraint(['village_id'], ['villages.id'], ),
    sa.ForeignKeyConstraint(['waterbody_type_id'], ['waterbody_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('waterbodies_census')
    op.drop_table('groundwater_extractions')
    op.drop_table('waterbody_types')
    # ### end Alembic commands ###
