"""add strange_runoff

Revision ID: 5c851b044498
Revises: bf1b715b26ca
Create Date: 2024-10-25 00:07:23.943727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c851b044498'
down_revision = 'bf1b715b26ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strange_runoff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rainfall_in_inches', sa.Integer(), nullable=True),
    sa.Column('rainfall_in_mm', sa.Float(), nullable=True),
    sa.Column('good_runoff', sa.Float(), nullable=True),
    sa.Column('average_runoff', sa.Float(), nullable=True),
    sa.Column('bad_runoff', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('strange_runoff')
    # ### end Alembic commands ###
