"""added approved col

Revision ID: b58c99de43f6
Revises: 5c6e6d9e8ff8
Create Date: 2024-12-06 13:56:17.221279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b58c99de43f6'
down_revision = '5c6e6d9e8ff8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('block_crops', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isApproved', sa.Boolean(), nullable=False))

    with op.batch_alter_table('block_groundwater', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isApproved', sa.Boolean(), nullable=False))

    with op.batch_alter_table('block_industries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isApproved', sa.Boolean(), nullable=False))

    with op.batch_alter_table('block_livestocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isApproved', sa.Boolean(), nullable=False))

    with op.batch_alter_table('block_lulc', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isApproved', sa.Boolean(), nullable=False))

    with op.batch_alter_table('block_populations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isApproved', sa.Boolean(), nullable=True))

    with op.batch_alter_table('block_rainfall', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isApproved', sa.Boolean(), nullable=False))

    with op.batch_alter_table('block_territory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isApproved', sa.Boolean(), nullable=True))

    with op.batch_alter_table('block_waterbodies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isApproved', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('block_waterbodies', schema=None) as batch_op:
        batch_op.drop_column('isApproved')

    with op.batch_alter_table('block_territory', schema=None) as batch_op:
        batch_op.drop_column('isApproved')

    with op.batch_alter_table('block_rainfall', schema=None) as batch_op:
        batch_op.drop_column('isApproved')

    with op.batch_alter_table('block_populations', schema=None) as batch_op:
        batch_op.drop_column('isApproved')

    with op.batch_alter_table('block_lulc', schema=None) as batch_op:
        batch_op.drop_column('isApproved')

    with op.batch_alter_table('block_livestocks', schema=None) as batch_op:
        batch_op.drop_column('isApproved')

    with op.batch_alter_table('block_industries', schema=None) as batch_op:
        batch_op.drop_column('isApproved')

    with op.batch_alter_table('block_groundwater', schema=None) as batch_op:
        batch_op.drop_column('isApproved')

    with op.batch_alter_table('block_crops', schema=None) as batch_op:
        batch_op.drop_column('isApproved')

    # ### end Alembic commands ###
