"""add crop_census

Revision ID: d8000f1ad33c
Revises: 4b8433d76e72
Create Date: 2024-11-01 22:18:05.628359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8000f1ad33c'
down_revision = '4b8433d76e72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crop_census',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('season', sa.String(length=80), nullable=True),
    sa.Column('area', sa.Float(), nullable=True),
    sa.Column('production', sa.Float(), nullable=True),
    sa.Column('crop_yield', sa.Float(), nullable=True),
    sa.Column('district_id', sa.Float(), nullable=True),
    sa.Column('state_id', sa.Float(), nullable=True),
    sa.Column('census_year', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crop_census')
    # ### end Alembic commands ###
