"""initial migrations

Revision ID: 8784f5aab1d2
Revises: 
Create Date: 2024-02-03 21:37:14.910658

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8784f5aab1d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('participants')
    op.drop_table('users')
    op.drop_index('ix_tokenblocklist_jti', table_name='tokenblocklist')
    op.drop_table('tokenblocklist')
    op.drop_table('events')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('event_id', sa.INTEGER(), server_default=sa.text("nextval('events_event_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('event_title', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('event_venue', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('event_address', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('event_date', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('event_time', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('event_id', name='events_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('tokenblocklist',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('jti', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='tokenblocklist_pkey')
    )
    op.create_index('ix_tokenblocklist_jti', 'tokenblocklist', ['jti'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('username', name='users_username_key')
    )
    op.create_table('participants',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fullname', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('designation', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('mobilenumber', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('district', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('block', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('grampanchayat', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], name='participants_event_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='participants_pkey'),
    sa.UniqueConstraint('email', name='participants_email_key'),
    sa.UniqueConstraint('mobilenumber', name='participants_mobilenumber_key')
    )
    op.drop_table('admin')
    # ### end Alembic commands ###
