"""second

Revision ID: 1dc55ece8ce8
Revises: a6bdf8f06073
Create Date: 2024-04-05 17:02:13.848121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dc55ece8ce8'
down_revision = 'a6bdf8f06073'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tga', sa.Column('district_id', sa.Integer(), nullable=False))
    op.add_column('tga', sa.Column('year_id', sa.Integer(), nullable=False))
    op.add_column('wl_area', sa.Column('wl_type_id', sa.Integer(), nullable=True))
    op.add_column('wl_area', sa.Column('district_id', sa.Integer(), nullable=True))
    op.add_column('wl_area', sa.Column('year_id', sa.Integer(), nullable=True))
    op.add_column('wl_type', sa.Column('wl_category_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wl_type', 'wl_category_id')
    op.drop_column('wl_area', 'year_id')
    op.drop_column('wl_area', 'district_id')
    op.drop_column('wl_area', 'wl_type_id')
    op.drop_column('tga', 'year_id')
    op.drop_column('tga', 'district_id')
    # ### end Alembic commands ###
