"""initial

Revision ID: a6bdf8f06073
Revises: 
Create Date: 2024-04-05 16:55:04.417691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6bdf8f06073'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('districts',
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('state_code', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('states',
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('tga',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tga', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wl_area',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wl_area', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wl_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wl_category', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wl_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wl_type', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('years',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('years')
    op.drop_table('wl_type')
    op.drop_table('wl_category')
    op.drop_table('wl_area')
    op.drop_table('tga')
    op.drop_table('states')
    op.drop_table('districts')
    # ### end Alembic commands ###
