"""users

Revision ID: d0298521ea35
Revises: 1dc55ece8ce8
Create Date: 2024-09-16 17:10:23.203933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0298521ea35'
down_revision = '1dc55ece8ce8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('in_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('states')
    op.drop_table('districts')
    op.drop_table('years')
    op.drop_table('tga')
    op.drop_table('wl_type')
    op.drop_table('wl_area')
    op.drop_table('wl_category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wl_category',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('wl_category', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='wl_category_pkey')
    )
    op.create_table('wl_area',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('wl_area', sa.REAL(), autoincrement=False, nullable=False),
    sa.Column('wl_type_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('district_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('year_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='wl_area_pkey')
    )
    op.create_table('wl_type',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('wl_type', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('wl_category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='wl_type_pkey')
    )
    op.create_table('tga',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tga', sa.REAL(), autoincrement=False, nullable=False),
    sa.Column('district_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('year_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='tga_pkey')
    )
    op.create_table('years',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('year', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='years_pkey')
    )
    op.create_table('districts',
    sa.Column('code', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('state_code', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('code', name='districts_pkey')
    )
    op.create_table('states',
    sa.Column('code', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('code', name='states_pkey')
    )
    op.drop_table('in_role')
    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###
