"""updated users table

Revision ID: 141becbd8a85
Revises: 4267ffa295d0
Create Date: 2025-02-12 16:52:00.292198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '141becbd8a85'
down_revision = '4267ffa295d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('district_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'districts', ['district_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('district_id')

    # ### end Alembic commands ###
