"""location migration

Revision ID: 3c582f0d0823
Revises: c2353c65b9fd
Create Date: 2025-02-04 12:01:46.541069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c582f0d0823'
down_revision = 'c2353c65b9fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lgd_code', sa.Integer(), nullable=True),
    sa.Column('state_name', sa.String(length=255), nullable=True),
    sa.Column('census_code', sa.Integer(), nullable=True),
    sa.Column('is_state', sa.Boolean(), nullable=True),
    sa.Column('short_name', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lgd_code')
    )
    op.create_table('districts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('state_lgd_code', sa.Integer(), nullable=False),
    sa.Column('lgd_code', sa.Integer(), nullable=False),
    sa.Column('district_name', sa.String(length=255), nullable=True),
    sa.Column('census_code', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['state_lgd_code'], ['states.lgd_code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lgd_code')
    )
    op.create_table('blocks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('state_lgd_code', sa.Integer(), nullable=False),
    sa.Column('district_lgd_code', sa.Integer(), nullable=False),
    sa.Column('lgd_code', sa.Integer(), nullable=False),
    sa.Column('block_name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['district_lgd_code'], ['districts.lgd_code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lgd_code'),
    sa.UniqueConstraint('lgd_code', 'district_lgd_code', name='blocks_unique_lgd_code_district_lgd_code')
    )
    op.create_table('panchayats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('state_lgd_code', sa.Integer(), nullable=False),
    sa.Column('district_lgd_code', sa.Integer(), nullable=False),
    sa.Column('block_lgd_code', sa.Integer(), nullable=False),
    sa.Column('lgd_code', sa.Integer(), nullable=False),
    sa.Column('panchayat_name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['block_lgd_code'], ['blocks.lgd_code'], ),
    sa.ForeignKeyConstraint(['district_lgd_code'], ['districts.lgd_code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lgd_code'),
    sa.UniqueConstraint('lgd_code', 'block_lgd_code', name='panchayats_unique_lgd_code_block_lgd_code')
    )
    op.create_table('villages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('state_lgd_code', sa.Integer(), nullable=False),
    sa.Column('district_lgd_code', sa.Integer(), nullable=False),
    sa.Column('lgd_code', sa.Integer(), nullable=False),
    sa.Column('village_name', sa.String(length=255), nullable=True),
    sa.Column('panchayat_lgd_code', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['district_lgd_code'], ['districts.lgd_code'], ),
    sa.ForeignKeyConstraint(['panchayat_lgd_code'], ['panchayats.lgd_code'], ),
    sa.ForeignKeyConstraint(['state_lgd_code'], ['states.lgd_code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lgd_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('villages')
    op.drop_table('panchayats')
    op.drop_table('blocks')
    op.drop_table('districts')
    op.drop_table('states')
    # ### end Alembic commands ###
