"""updated users

Revision ID: 4267ffa295d0
Revises: b168da47a700
Create Date: 2025-02-12 14:22:46.320281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4267ffa295d0'
down_revision = 'b168da47a700'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('livestock_census', schema=None) as batch_op:
        batch_op.alter_column('panchayat_code',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('panchayats', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'states', ['state_lgd_code'], ['lgd_code'])

    with op.batch_alter_table('rainfall_data', schema=None) as batch_op:
        batch_op.alter_column('month_year',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('year')
        batch_op.drop_column('month')

    with op.batch_alter_table('territory_joins', schema=None) as batch_op:
        batch_op.drop_column('rec_status')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('panchayat_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('users_district_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'panchayats', ['panchayat_id'], ['id'])
        batch_op.drop_column('district_id')

    with op.batch_alter_table('villages', schema=None) as batch_op:
        batch_op.alter_column('block_lgd_code',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(None, 'blocks', ['block_lgd_code'], ['lgd_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('villages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('block_lgd_code',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('district_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('users_district_id_fkey', 'districts', ['district_id'], ['id'])
        batch_op.drop_column('panchayat_id')

    with op.batch_alter_table('territory_joins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rec_status', sa.BOOLEAN(), autoincrement=False, nullable=True))

    with op.batch_alter_table('rainfall_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('month', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.alter_column('month_year',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('panchayats', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('livestock_census', schema=None) as batch_op:
        batch_op.alter_column('panchayat_code',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
