"""masters and territory

Revision ID: 6c15cc8c5b1b
Revises: 3c582f0d0823
Create Date: 2025-02-04 12:04:17.218911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c15cc8c5b1b'
down_revision = '3c582f0d0823'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crop_name', sa.String(length=200), nullable=False),
    sa.Column('coefficient', sa.Float(), nullable=False),
    sa.Column('remarks', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crop_name')
    )
    op.create_table('industries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('industry_sector', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('industry_sector')
    )
    op.create_table('livestocks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('livestock_name', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('coefficient', sa.Float(), nullable=False),
    sa.Column('remarks', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('livestock_name')
    )
    op.create_table('lulc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lulc_name', sa.String(length=100), nullable=False),
    sa.Column('census_description', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('catchment', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lulc_name')
    )
    op.create_table('population',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('population_type', sa.String(length=100), nullable=False),
    sa.Column('short_name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strange_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rainfall_in_inches', sa.Integer(), nullable=True),
    sa.Column('rainfall_in_mm', sa.Float(), nullable=True),
    sa.Column('good_runoff', sa.Float(), nullable=True),
    sa.Column('average_runoff', sa.Float(), nullable=True),
    sa.Column('bad_runoff', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('waterbody_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('waterbody_name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=300), nullable=True),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('isAdmin', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('territory_joins',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=True),
    sa.Column('panchayat_id', sa.Integer(), nullable=True),
    sa.Column('village_id', sa.Integer(), nullable=False),
    sa.Column('rec_status', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.ForeignKeyConstraint(['panchayat_id'], ['panchayats.id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ),
    sa.ForeignKeyConstraint(['village_id'], ['villages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('territory_joins')
    op.drop_table('users')
    op.drop_table('waterbody_types')
    op.drop_table('strange_table')
    op.drop_table('population')
    op.drop_table('lulc')
    op.drop_table('livestocks')
    op.drop_table('industries')
    op.drop_table('crops')
    # ### end Alembic commands ###
