"""updated bt table

Revision ID: 8f94e7ad20fd
Revises: 141becbd8a85
Create Date: 2025-02-13 00:15:25.600109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f94e7ad20fd'
down_revision = '141becbd8a85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('block_territory', schema=None) as batch_op:
        batch_op.drop_constraint('block_territory_block_id_key', type_='unique')
        batch_op.create_unique_constraint(None, ['village_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('block_territory', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('block_territory_block_id_key', ['block_id'])

    # ### end Alembic commands ###
