"""initial migration

Revision ID: c2353c65b9fd
Revises: 
Create Date: 2025-02-04 11:47:31.142936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2353c65b9fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('states')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('states',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lgd_code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('state_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('census_code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_state', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('short_name', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='states_pkey'),
    sa.UniqueConstraint('lgd_code', name='states_lgd_code_key')
    )
    # ### end Alembic commands ###
